import * as THREE from 'three';
import {solarPosition,formatHour} from './solar.js';
export function createEnvironment({scene,resort,sun,hemisphere,renderer,ground,glass,waterMat,fly}){
 let hour=16.5,playing=false,showOverride=false,eventsVisible=true,last=-1,phase=0,lastMode=null,activeShow=false;
 const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
 const sky=new THREE.Mesh(new THREE.SphereGeometry(680,32,20),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{zenith:{value:new THREE.Color('#4e83a4')},horizon:{value:new THREE.Color('#e6dbc3')}},vertexShader:'varying vec3 p;void main(){p=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 p;uniform vec3 zenith;uniform vec3 horizon;void main(){float h=pow(clamp(normalize(p).y,0.,1.),.45);gl_FragColor=vec4(mix(horizon,zenith,h),1.);}'}));scene.add(sky);
 const solarDisc=new THREE.Mesh(new THREE.SphereGeometry(6,20,16),new THREE.MeshBasicMaterial({color:'#fff1c2',fog:false}));scene.add(solarDisc);
 const moon=new THREE.Mesh(new THREE.SphereGeometry(3.7,16,12),new THREE.MeshBasicMaterial({color:'#c5d8ef',fog:false}));moon.position.set(-160,250,-330);scene.add(moon);
 const positions=new Float32Array(360*3);for(let i=0;i<360;i++){const a=i*2.39996,h=.18+((i*73)%359)/359*.78,r=Math.sqrt(1-h*h)*600;positions.set([Math.cos(a)*r,h*600,Math.sin(a)*r],i*3);}const starGeo=new THREE.BufferGeometry();starGeo.setAttribute('position',new THREE.BufferAttribute(positions,3));const stars=new THREE.Points(starGeo,new THREE.PointsMaterial({color:'#d5e7ff',size:1.2,fog:false,transparent:true,opacity:0}));scene.add(stars);
 const eventGroup=new THREE.Group();resort.add(eventGroup);const lightGroup=new THREE.Group();resort.add(lightGroup);
 const mat=(color,props={})=>new THREE.MeshStandardMaterial({color,roughness:.7,...props});
 const add=(geo,material,pos,parent=eventGroup)=>{const o=new THREE.Mesh(geo,material);o.position.set(...pos);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;};
 const wood=mat('#66513d'),metal=mat('#293c3d',{metalness:.7}),cream=mat('#cbbda0');
 const bulbMaterial=new THREE.MeshBasicMaterial({color:'#ffd796'});
 for(let i=0;i<28;i++){const a=Math.PI*.1+i/27*Math.PI*1.8,x=Math.cos(a)*83,z=Math.sin(a)*74+11;add(new THREE.CylinderGeometry(.14,.2,3.2,8),metal,[x,1.6,z],lightGroup);add(new THREE.SphereGeometry(.42,10,8),bulbMaterial,[x,3.25,z],lightGroup);const pool=new THREE.Mesh(new THREE.CircleGeometry(2.7,20),new THREE.MeshBasicMaterial({color:'#f9ce86',transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}));pool.rotation.x=-Math.PI/2;pool.position.set(x,.13,z);lightGroup.add(pool);}
 for(let i=0;i<7;i++){const x=-32+i*10,z=80-Math.abs(x)*.17;add(new THREE.BoxGeometry(3.3,.3,.9),wood,[x,.8,z]);for(const dx of [-1.2,1.2])add(new THREE.BoxGeometry(.16,.8,.6),metal,[x+dx,.35,z]);}
 const bannerCanvas=document.createElement('canvas');bannerCanvas.width=1536;bannerCanvas.height=512;const bc=bannerCanvas.getContext('2d');bc.fillStyle='#102c32';bc.fillRect(0,0,1536,512);bc.fillStyle='#d8ef99';bc.font='bold 130px sans-serif';bc.fillText('BOLD MAKER',90,190);bc.font='500 64px sans-serif';bc.fillText('2026  影石 Insta360',96,300);bc.font='42px sans-serif';bc.fillText('智能影像挑战赛  ·  开图 UNFOLD',98,405);const bannerTexture=new THREE.CanvasTexture(bannerCanvas);bannerTexture.colorSpace=THREE.SRGBColorSpace;
 const board=add(new THREE.BoxGeometry(17,5.7,.28),mat('#1e393e'),[-54,3.5,1]);const label=new THREE.Mesh(new THREE.PlaneGeometry(17,5.7),new THREE.MeshBasicMaterial({map:bannerTexture}));label.position.set(0,0,.16);board.add(label);for(const x of [-61,-47])add(new THREE.CylinderGeometry(.14,.14,3,8),metal,[x,1,1]);
 // Entrance gate and event flags are proposal elements, awaiting tomorrow's photos.
 const gate=new THREE.Group();gate.position.set(-7,.3,-64);eventGroup.add(gate);
 for(const x of [-9,9])add(new THREE.BoxGeometry(.5,7,.5),wood,[x,3.5,0],gate);add(new THREE.BoxGeometry(19,.5,1.4),wood,[0,7,0],gate);
 for(let i=0;i<5;i++){const x=48+i*5,z=4+i*1.4;add(new THREE.CylinderGeometry(.1,.1,7,8),metal,[x,3.5,z]);const flag=add(new THREE.PlaneGeometry(1.8,4),new THREE.MeshStandardMaterial({map:bannerTexture,side:THREE.DoubleSide,roughness:.8}),[x+.9,4.9,z]);flag.rotation.y=-.3;}
 // Road edge, rails, planting strips and entry paving add scale cues.
 for(let i=0;i<34;i++){const a=Math.PI*1.01+i/33*Math.PI*.98,x=Math.cos(a)*78,z=Math.sin(a)*78+19;add(new THREE.BoxGeometry(.5,.6,.5),cream,[x,.4,z]);}
 const show=new THREE.Group();resort.add(show);show.visible=false;
 const jets=[];for(let i=0;i<45;i++){const color=new THREE.Color().setHSL(i/55+.51,.9,.6),material=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.78,blending:THREE.AdditiveBlending,depthWrite:false});const jet=new THREE.Mesh(new THREE.CylinderGeometry(.07,.19,1,6),material);jet.position.set((i-22)*1.15,0,35);show.add(jet);jets.push(jet);}
 const curtain=new THREE.Mesh(new THREE.PlaneGeometry(52,22,64,32),new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,uniforms:{time:{value:0}},vertexShader:'varying vec2 v;void main(){v=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec2 v;uniform float time;void main(){vec2 p=vec2((v.x-.5)*2.,v.y);float r=length(p);float a=atan(p.x,p.y);float rays=pow(abs(sin(a*31.+time*.35)),6.);float mist=(.32+.68*rays)*(1.-smoothstep(.60,1.12,r));float edge=smoothstep(0.,.12,p.y);vec3 c=.55+.45*cos(time*.7+a*2.+vec3(0.,2.,4.));float ripple=.6+.4*sin(p.y*45.-time*3.+p.x*9.);gl_FragColor=vec4(c,mist*edge*ripple*.45);}`}));curtain.position.set(0,11,34.8);show.add(curtain);
 const projection=new THREE.Mesh(new THREE.PlaneGeometry(17,5.7),new THREE.MeshBasicMaterial({map:bannerTexture,transparent:true,opacity:.55,blending:THREE.AdditiveBlending,depthWrite:false,side:THREE.DoubleSide}));projection.position.set(0,8,35.1);show.add(projection);
 const particleCount=2000,particlePositions=new Float32Array(particleCount*3),particleColors=new Float32Array(particleCount*3);const particleGeo=new THREE.BufferGeometry();particleGeo.setAttribute('position',new THREE.BufferAttribute(particlePositions,3));particleGeo.setAttribute('color',new THREE.BufferAttribute(particleColors,3));const particles=new THREE.Points(particleGeo,new THREE.PointsMaterial({size:.17,vertexColors:true,transparent:true,opacity:.75,depthWrite:false,blending:THREE.AdditiveBlending}));show.add(particles);
 const reflection=new THREE.Mesh(new THREE.PlaneGeometry(62,44),new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{time:{value:0}},vertexShader:'varying vec2 v;void main(){v=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 v;uniform float time;void main(){float line=pow(abs(sin(v.x*95.+sin(v.y*53.+time)*.6+time*.4)),13.);float fade=(1.-abs(v.x-.5)*2.)*pow(v.y,1.3);vec3 c=.5+.5*cos(v.x*8.+time*.7+vec3(0.,2.,4.));gl_FragColor=vec4(c,line*fade*.35);}'}));reflection.rotation.x=-Math.PI/2;reflection.position.set(0,.03,54);show.add(reflection);
 const skyDay=new THREE.Color('#a9cbdc'),skyNight=new THREE.Color('#091326'),skyDusk=new THREE.Color('#a97d81');
 function updateLight(){const p=solarPosition(hour),day=THREE.MathUtils.smoothstep(p.elevation,-5,28),twilight=Math.max(0,1-Math.abs(p.elevation-1)/13),nightAmount=1-day;
  sun.position.set(...p.direction.map(v=>v*210));sun.intensity=p.elevation>0?2.7*Math.pow(p.daylight,.4):0;sun.color.setRGB(1,1-.37*twilight,1-.64*twilight);
  hemisphere.intensity=.14+day*1.1;hemisphere.color.set(day>.4?'#dce8ee':'#7896bc');hemisphere.groundColor.set(day>.4?'#657862':'#172438');
  scene.environmentIntensity=.08+day*.42;renderer.toneMappingExposure=.78+day*.2;
  scene.background.copy(skyNight).lerp(skyDay,day).lerp(skyDusk,twilight*.4);if(scene.fog)scene.fog.color.copy(scene.background);
  sky.material.uniforms.zenith.value.copy(skyNight).lerp(new THREE.Color('#6899b4'),day);sky.material.uniforms.horizon.value.copy(scene.background);ground.material.color.copy(scene.background).multiplyScalar(.63+day*.3);
  solarDisc.visible=p.elevation>-.02;solarDisc.position.set(...p.direction.map(v=>v*520));solarDisc.material.color.copy(sun.color);moon.visible=day<.2;stars.material.opacity=nightAmount*.8;
  glass.emissive.set('#eba855');glass.emissiveIntensity=nightAmount*.72;waterMat.uniforms.night.value=nightAmount;
  lightGroup.traverse(o=>{if(o.isMesh&&o.material.transparent)o.material.opacity=nightAmount*.27;});bulbMaterial.color.set(day>.4?'#d5d2ab':'#ffd690');
  document.querySelector('.world')?.classList.toggle('night',day<.35);const label=document.querySelector('#time-value');if(label)label.textContent=formatHour(hour);const slider=document.querySelector('#time-slider');if(slider&&document.activeElement!==slider)slider.value=String(hour);const phaseEl=document.querySelector('#time-phase');if(phaseEl)phaseEl.textContent=p.elevation>6?'日间':p.elevation>-6?'晨昏':'夜间';
 }
 function tick(time,dt,mode,venue="xianlin"){if(mode!==lastMode){last=-1;lastMode=mode;}if(playing&&mode==='resort')hour=(hour+dt*.2)%24;if(last!==Math.floor(hour*240)){updateLight();last=Math.floor(hour*240);if(mode!=='resort'){sun.position.set(-90,170,80);sun.intensity=2.5;sun.color.set('#fff3cf');hemisphere.intensity=1.3;scene.environmentIntensity=.5;renderer.toneMappingExposure=1;scene.background.set('#dce6dc');ground.material.color.set('#dce6dc');glass.emissiveIntensity=0;document.querySelector('.world')?.classList.remove('night');}}sky.visible=mode==='resort';solarDisc.visible=mode==='resort'&&solarPosition(hour).elevation>0;moon.visible=mode==='resort'&&hour<6||mode==='resort'&&hour>19;stars.visible=mode==='resort';eventGroup.visible=eventsVisible;
  const active=mode==='resort'&&venue==='xianlin'&&(showOverride||playing&&hour>=19.5&&hour<20.5);show.visible=active;activeShow=active;const showButton=document.querySelector('#water-show');if(showButton){showButton.classList.toggle('active',active);showButton.setAttribute('aria-pressed',String(active));}const indicator=document.querySelector('#show-state');if(indicator)indicator.textContent=venue!=='xianlin'?'街景灯光与晨昏预演':active?'水幕预演中':'19:30 效果预演';
  if(!active)return;phase=reduced?3:time/1000;curtain.material.uniforms.time.value=phase;reflection.material.uniforms.time.value=phase;projection.material.opacity=.23+.15*Math.sin(phase*.7);
  jets.forEach((jet,i)=>{const h=2+Math.pow(Math.sin(i/44*Math.PI),.7)*(7+6*Math.sin(phase*.7+i*.19)**2);jet.scale.y=h;jet.position.y=h*.5;jet.material.color.setHSL((i/65+phase*.04)%1,.85,.6);});
  const c=new THREE.Color();for(let i=0;i<particleCount;i++){const lane=i%45,t=((i*.618+phase*.6)%1),h=jets[lane].scale.y;particlePositions[i*3]=(lane-22)*1.15+Math.sin(i*7)*t*.6;particlePositions[i*3+1]=4*t*(1-t)*h;particlePositions[i*3+2]=35+Math.sin(i*2.4)*t*2;c.setHSL((lane/65+phase*.04)%1,.7,.7);particleColors.set([c.r,c.g,c.b],i*3);}particleGeo.attributes.position.needsUpdate=true;particleGeo.attributes.color.needsUpdate=true;
 }
 updateLight();
 return{tick,get showActive(){return activeShow;},get hour(){return hour;},get playing(){return playing;},setTime(h){hour=THREE.MathUtils.clamp(Number(h),0,24);playing=false;showOverride=false;last=-1;updateLight();},toggleDay(){playing=!playing;showOverride=false;return playing;},show(){playing=false;showOverride=!showOverride;if(showOverride){hour=19.5;last=-1;updateLight();fly([0,28,126],[0,7,33]);}return showOverride;},toggleEvents(){eventsVisible=!eventsVisible;return eventsVisible;}};
}
