import {getVenue,getPlan,plans,offers,getOffer} from './venues.js';
import {recommend} from './recommendations.js';
import {loadCommerce,issueCoupon,redeemCoupon,metrics,storageKey} from './commerce.js';
import {escapeHtml as esc,downloadJson} from './utils.js';
export function createExperience({world,toast,switchTab,restoreScene,assistant}){
 let panel,venue='xianlin',selected=plans[0],mode='内置策划示例',explanation='',lastCoupon=null;
 let storage;try{storage=localStorage;}catch{storage={getItem:()=>null,setItem:()=>{}};}const state=loadCommerce(storage);const save=()=>{try{storage.setItem(storageKey,JSON.stringify(state));}catch{toast('浏览器未允许保存，本次操作仅保留在当前页面。');}};
 const $=s=>panel?.querySelector(s);
 function event(type){state.events.push({type,venue,seed:false,at:new Date().toISOString()});save();}
 function setVenue(id){venue=id;selected=plans.find(p=>p.venue===id);mode='内置策划示例';explanation='';event('view');}
 function selectPlan(id,show=true){const plan=getPlan(id);if(!plan||plan.venue!==venue)return;selected=plan;event('plan');if(show){restoreScene();world?.environment.setTime(plan.hour);world?.drawJourney(plan.stops);}renderVisitor(panel);}
 function offerCard(o){return `<article class="offer-card"><div class="dish-art" style="--dish:${o.color}"><span>${o.symbol}</span><small>示例套餐</small></div><div class="offer-content"><span class="offer-merchant">${o.merchant}</span><h4>${o.name}</h4><p>${o.items.join(' · ')}</p><div class="offer-price"><strong><small>¥</small>${o.price}</strong><span>${o.people} 人份</span><button class="coupon-btn" data-claim="${o.id}">领演示券 ↗</button></div></div></article>`;}
 function renderVisitor(target){panel=target;const v=getVenue(venue),all=plans.filter(p=>p.venue===venue),p=selected;
 panel.innerHTML=`<div class="work-title"><h3>把想去，变成一份行程。</h3><span>AI × TASTE</span></div><p class="work-lead">告诉开图你的想法，把景色、停留点和餐饮放进同一条路线。</p><form id="ask-form" class="ask-box"><label for="ask-query">今天想怎么逛？</label><textarea id="ask-query" rows="2" maxlength="500">${esc(p.prompt)}</textarea><div><span>本地意图识别</span><button type="submit">生成方案 ↗</button></div></form><div class="preset-list">${all.map(x=>`<button data-preset="${x.id}" class="${x.id===p.id?'selected':''}">${x.prompt}</button>`).join('')}</div><details class="ai-details"><summary>AI 如何参与？</summary><p>预置行程打开即可演示。输入需求时，本地朴素贝叶斯模型识别意图，再用人数、时间、预算和禁忌规则筛选方案。不会虚构店铺或过敏安全信息。</p><p>部署后台并配置模型后，可在影像工作台连接服务，再点击下方按钮调用实时模型；密钥只放在服务器。</p><button id="live-ai" class="secondary">使用已配置的实时 AI</button></details>${explanation?`<p class="recommend-feedback" role="status">${esc(explanation)}</p>`:''}<div class="journey-card"><div class="journey-eyebrow">${esc(mode)} <span>0${all.indexOf(p)+1} / 03</span></div><h3>${p.title}</h3><div class="journey-numbers"><span><b>${p.duration}</b> 分钟</span><span><b>¥${p.budget}</b> 餐饮合计</span><span><b>${p.people}</b> 人</span></div><p>${p.narration}</p><ol class="stop-list">${p.stops.map((id,i)=>`<li><button data-stop="${id}"><span>${i+1}</span>${v.places.find(x=>x.id===id).name}<b>↗</b></button></li>`).join('')}</ol><button class="primary" id="show-journey">在场景中展开路线 <span>↗</span></button><div class="actions"><button class="secondary" id="speak-plan">▶ 听行程介绍</button><button class="secondary" id="export-plan">保存行程卡 ↓</button></div><details class="why-details"><summary>为什么这样安排？</summary><ul>${p.why.map(x=>`<li>${x}</li>`).join('')}</ul></details></div><div class="section-heading commerce-heading">顺路吃点好的 <span>${p.offerIds.length} 份示例</span></div>${p.offerIds.map(id=>offerCard(getOffer(id))).join('')}${lastCoupon&&lastCoupon.venue===venue?`<div class="coupon-ticket" role="status"><span>演示券已领取 · 无支付</span><strong>${getOffer(lastCoupon.offerId).name}</strong><code>${lastCoupon.id}</code><button class="primary" id="go-redeem">去商家台核销这张券 →</button></div>`:''}<p class="source-note">商家、套餐、价格及券均为演示设定，不可消费。不含门票，停留时长为建议；当前参考路网不可用于现场导航。</p>`;
 panel.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{mode='内置策划示例';explanation='';selectPlan(b.dataset.preset);});
 panel.querySelectorAll('[data-stop]').forEach(b=>b.onclick=()=>{restoreScene();world?.focus(b.dataset.stop);});
 $('#ask-form').onsubmit=e=>{e.preventDefault();const r=recommend(venue,$('#ask-query').value);explanation=r.reason;if(r.plan){mode='本地模型 · 已校验';selectPlan(r.plan.id);}else{mode='无匹配 · 下方为已有示例';renderVisitor(panel);toast(r.reason);}};
 $('#live-ai').onclick=async e=>{const b=e.currentTarget,query=$('#ask-query').value;b.disabled=true;b.textContent='AI 正在选择方案…';try{const r=await assistant(venue,query);if(r.planId){mode='实时 AI · '+r.model;explanation='实时模型选择了目录内方案，金额来自固定套餐数据。';selectPlan(r.planId);}else toast('实时 AI 未找到满足条件的示例方案。');}catch(error){toast(error.message);}finally{if(b.isConnected){b.disabled=false;b.textContent='使用已配置的实时 AI';}}};
 $('#show-journey').onclick=()=>{restoreScene();world?.environment.setTime(p.hour);world?.drawJourney(p.stops);event('plan');toast('金色线条已连接行程点位，点击行程中的站点可近看。');};
 $('#speak-plan').onclick=()=>{if(!('speechSynthesis'in window))return toast('当前浏览器不支持语音播报。');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(p.narration);u.lang='zh-CN';u.rate=.95;speechSynthesis.speak(u);toast('正在使用浏览器语音朗读内置行程，非实时 AI 语音。');};
 $('#export-plan').onclick=()=>exportCard(p,v);
 panel.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>{lastCoupon=issueCoupon(state,b.dataset.claim,'DEMO-'+crypto.randomUUID().slice(0,8).toUpperCase());save();renderVisitor(panel);$('#go-redeem')?.scrollIntoView({behavior:'smooth',block:'nearest'});toast('演示券已保存在本机，下一步可到商家台核销。');});
 if($('#go-redeem'))$('#go-redeem').onclick=()=>switchTab('merchant');
 }
 function renderMerchant(target){panel=target;const m=metrics(state,venue),v=getVenue(venue),coupons=state.coupons.filter(c=>c.venue===venue).slice().reverse(),own=coupons.filter(c=>!c.seed),funnel=[['场景浏览',m.views],['行程选择',m.plans],['示例领券',m.claims],['示例核销',m.redeemed]];
 panel.innerHTML=`<div class="work-title"><h3>让一次浏览，有下一步。</h3><span>MERCHANT STUDIO</span></div><p class="work-lead">${v.name} · 场地与餐饮商家的运营沙盘。包含示例底稿，领券和核销会立即更新。</p><span class="data-label">本机沙盘 · 无支付 · 无真实订单</span><div class="metric-grid"><div><strong>${m.plans}</strong><span>选择行程</span></div><div><strong>${m.claims}</strong><span>已领演示券</span></div><div><strong>${m.redeemed}</strong><span>已核销</span></div><div><strong>¥${m.value}</strong><span>核销套餐面额 · 非收入</span></div></div><h4 class="section-heading">从看见，到到店 <span>含示例底稿</span></h4><div class="funnel">${funnel.map(([name,n])=>`<div><span>${name}</span><i style="--bar:${Math.max(5,n/Math.max(...funnel.map(x=>x[1]),1)*100)}%"></i><b>${n}</b></div>`).join('')}</div><div class="work-callout">本次真实点击：领券 ${own.length} 张、核销 ${own.filter(c=>c.status==='redeemed').length} 张。底稿仅用于展示运营界面，不代表实际客流。</div><div class="section-heading commerce-heading">核销工作台 <span>点击即可演示</span></div><div class="coupon-list">${coupons.map(c=>`<article class="redeem-row ${c.id===lastCoupon?.id?'latest':''}"><div><strong>${getOffer(c.offerId).name}</strong><small>${c.seed?'示例底稿':'本次演示'} · ¥${getOffer(c.offerId).price}</small><code>${c.id}</code></div><button data-redeem="${c.id}" ${c.status==='redeemed'?'disabled':''}>${c.status==='redeemed'?'已核销 ✓':'确认核销'}</button></article>`).join('')}</div><div class="actions"><button class="secondary" id="export-ops">导出沙盘数据 ↓</button><button class="secondary" id="back-visitor">回到游客端 ↗</button></div><div class="business-model"><span class="eyebrow">HOW IT BECOMES A BUSINESS</span><h3>卖上线服务，<br/>也卖持续运营。</h3><p><b>给场地方</b> · 影像采集、空间上线与更新服务。</p><p><b>给商户</b> · 套餐内容、路线推荐入口与核销台订阅。</p><p><b>验证价值</b> · 先衡量推荐后领券与到店核销，再讨论合作分成。</p><small>上线运营前接入真实商户、营业信息、服务端券账本和账号权限。当前商业流程为本机演示。</small></div>`;
 panel.querySelectorAll('[data-redeem]').forEach(b=>b.onclick=()=>{const changed=redeemCoupon(state,b.dataset.redeem);save();renderMerchant(panel);toast(changed?'已核销：券状态与运营看板已同步更新。':'这张券已经核销，未重复计入。');});
 $('#back-visitor').onclick=()=>switchTab('food');$('#export-ops').onclick=()=>downloadJson({type:'demo-only-not-sales',venue,metrics:m,coupons,events:state.events.filter(e=>e.venue===venue)},'kaitu-demo-operations.json');
 }
 function exportCard(p,v){const canvas=document.createElement('canvas');canvas.width=1000;canvas.height=1320;const c=canvas.getContext('2d');c.fillStyle='#f1efdf';c.fillRect(0,0,1000,1320);c.fillStyle='#163b38';c.fillRect(0,0,1000,230);c.fillStyle='#d6e99f';c.font='bold 60px sans-serif';c.fillText('开图  /  '+v.name,65,115);c.font='22px sans-serif';c.fillText('UNFOLD · A WALK WORTH TAKING',68,172);c.fillStyle='#183c35';c.font='bold 36px sans-serif';c.fillText(p.title,65,310);c.font='26px sans-serif';c.fillText(p.duration+' 分钟  ·  '+p.people+' 人  ·  餐饮示例 ¥'+p.budget,65,368);p.stops.forEach((id,i)=>{const y=460+i*86;c.fillStyle='#6c8361';c.beginPath();c.arc(85,y-8,19,0,Math.PI*2);c.fill();c.fillStyle='#fff';c.font='22px sans-serif';c.fillText(String(i+1),79,y);c.fillStyle='#193e38';c.font='28px sans-serif';c.fillText(v.places.find(x=>x.id===id).name,132,y);});c.font='24px sans-serif';p.offerIds.forEach((id,i)=>{const o=getOffer(id);c.fillText(o.name+' · 示例 ¥'+o.price,65,1040+i*43);});c.fillStyle='#6c7d6e';c.font='19px sans-serif';c.fillText('示例行程与虚构套餐 · 不可用于消费或实地导航',65,1220);c.fillText('Insta360 X4 Air 采集工作流 × 开图空间服务原型',65,1255);canvas.toBlob(blob=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=p.id+'-journey.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'image/png');toast('行程卡已导出，包含路线点位与示例餐饮预算。');}
 return{setVenue,renderVisitor,renderMerchant,selectPlan,get plan(){return selected;}};
}
