import './style.css';
import './illustration.css';
import {createMediaLibrary} from './media.js';
import {createWorld} from './scene.js';
import {createWorkbench} from './workbench.js';
import {createExperience} from './experience.js';
import {venues,getVenue} from './venues.js';
import {sources} from './data.js';
const $=s=>document.querySelector(s);
let media;
let tab='explore',venueId='xianlin',selected='resort',world,workbench,experience,toastTimer;
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),6000);}
function sceneCopy(){const v=getVenue(venueId);document.body.dataset.venue=venueId;document.querySelector('.world').classList.remove('asset-view');$('#scene-title').textContent=v.headline;$('#scene-subtitle').textContent=v.fullName+' / '+v.season;$('#evidence-chip').textContent='公开资料参考重绘 · 待实拍校准';$('#scene-note').textContent=v.id==='qixia'?'秋色为艺术预演 · 非当前实况 · 路线待测量':v.id==='mendong'?'街巷风貌参考 · 商铺与套餐为演示':'建筑待实拍校准 · 水幕与布展为创意预演';$('.time-console').hidden=false;$('#water-show').hidden=venueId!=='xianlin';$('#time-venue').textContent=v.name+' · 光影时刻';syncTime();}
function renderRail(){$('#venue-selector').innerHTML=venues.map((v,i)=>`<button data-venue="${v.id}" class="venue-choice ${v.id===venueId?'active':''}" aria-pressed="${v.id===venueId}"><i class="destination-art art-${v.id}" aria-hidden="true"></i><span><small class="destination-number">0${i+1} / NANJING</small><strong>${v.name}</strong><small>${v.theme}</small></span><b>↗</b></button>`).join('');document.querySelectorAll('[data-venue]').forEach(b=>b.onclick=()=>changeVenue(b.dataset.venue));}
function changeVenue(id){if(id===venueId)return;window.speechSynthesis?.cancel();venueId=id;selected=getVenue(id).places[0].id;try{world?.switchVenue(id);}catch(e){console.error(e);toast('场景加载失败，请刷新后重试。');}experience.setVenue(id);renderRail();render();sceneCopy();}
function selectPlace(id){selected=id;world?.focus(id);sceneCopy();if(tab==='explore')render();else toast(getVenue(venueId).places.find(p=>p.id===id)?.name||'已切换视角');}
function render(){const panel=$('#panel'),v=getVenue(venueId);$('.sidebar').className='sidebar '+tab;
 if(tab==='explore'){
 panel.innerHTML=`<button class="real-world-card" id="open-real-world"><span>◎</span><div><strong>看看真实的${v.name}</strong><small>${v.id==='xianlin'?'官方资料 + 现场采集指引':'实景照片 · 全景检索记录'}</small></div><b>↗</b></button><div class="purpose-strip"><span>给游客 · 逛得明白</span><span>给商家 · 看见转化</span></div><button class="primary demo-start" id="start-demo">一键演示：${v.id==='xianlin'?'亲子湖畔行':v.id==='qixia'?'赏秋与茶点':'金陵逛吃'} <span>↗</span><small>选行程 → 看路线 → 领券 → 核销</small></button><div class="section-heading explore-heading">走近${v.name} <span>${v.places.length} 个空间锚点</span></div>${v.places.map((p,i)=>`<button class="place ${selected===p.id?'selected':''}" data-place="${p.id}"><span class="place-index">0${i+1}</span><span class="place-text"><strong>${p.name}</strong><small>${p.type==='food'?'餐饮服务点':p.type==='view'?'风景与影像':'建筑与地标'}</small></span><span class="place-arrow">↗</span></button>`).join('')}<div class="place-detail"><b>${v.places.find(p=>p.id===selected)?.name||v.name}</b><br/>${v.places.find(p=>p.id===selected)?.detail||v.summary}</div><div class="explore-note"><b>从现场，到服务</b><p>${v.commercial}。用 X4 Air 记录空间，将实拍影像替换进导览，保留同一套服务入口。</p><button class="secondary" id="start-capture">打开影像工作台 ↗</button>${v.id==='xianlin'?'<p><button class="text-button" id="toggle-events">显示 / 隐藏赛事布展</button></p>':''}</div>`;
 panel.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>selectPlace(b.dataset.place));$('#open-real-world').onclick=()=>media.open();$('#start-demo').onclick=()=>{switchTab('food');experience.selectPlan(experience.plan.id);};$('#start-capture').onclick=()=>switchTab('capture');if($('#toggle-events'))$('#toggle-events').onclick=()=>toast(world?.environment.toggleEvents()?'已显示赛事布展提案':'已隐藏赛事布展');
 }else if(tab==='capture')workbench.render(panel);
 else if(tab==='food')experience.renderVisitor(panel);
 else if(tab==='merchant')experience.renderMerchant(panel);
 else panel.innerHTML=`<a class="manual-card" href="/docs/kaitu-product-manual.pdf" target="_blank" rel="noopener">↗ 路演产品说明书 <small>产品 · 影像 · 商业化 · 演示脚本</small></a><a class="source-card" href="/ASSET_LICENSES.md" target="_blank" rel="noopener">实拍素材来源与授权清单 ↗</a><div class="work-title"><h3>看得见，也有依据。</h3><span>FIELD ARCHIVE</span></div><span class="data-label">${v.evidence}</span><p class="work-lead">${v.summary}</p><a class="source-card" href="${v.sourceUrl}" target="_blank" rel="noopener">${v.sourceTitle} ↗<small>公开建筑、环境与地标参考</small></a>${v.id==='xianlin'?sources.map(s=>`<a class="source-card" href="${s.url}" target="_blank" rel="noopener">${s.title} ↗<small>${s.label}</small></a>`).join(''):''}<div class="evidence-row"><b>已落地的视觉技术</b><span>Three.js PBR 材质、平面水体反射、GTAO 环境遮蔽、夜景 Bloom、批量树木与静态几何合并、风动植被和晨昏光照。可在右侧切换画质。</span></div><div class="evidence-row"><b>模型精度</b><span>当前是按公开资料构建的风貌模型，未获得完整测绘图、真实材质贴图和相机位姿。细节增加不等同于测量精度提升。</span></div><div class="evidence-row"><b>下一轮现场补充</b><span>${v.capture}。补拍入口立面、导览牌、固定锚点与一段实测距离；店铺名称、餐饮配方、价格与开放信息由运营方确认。</span></div><div class="evidence-row"><b>光照与活动</b><span>南京太阳轨迹近似计算；场地北向尚待校准。栖霞秋色、夜景灯光和水幕均为预演，非实时状态。</span></div><a class="source-card" href="https://www.insta360.com/cn/product/insta360-x4-air" target="_blank" rel="noopener">Insta360 X4 Air 官方产品参数 ↗</a><a class="source-card" href="https://threejs.org/docs/pages/GTAOPass.html" target="_blank" rel="noopener">Three.js GTAO 与渲染技术 ↗</a>`;
}
function switchTab(next){window.speechSynthesis?.cancel();tab=next;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.tab===next));render();$('.sidebar').scrollTop=0;if(next!=='capture'&&world?.mode==='asset'){world.overview();sceneCopy();}}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>switchTab(b.dataset.tab);
$('#help').onclick=()=>$('#help-dialog').showModal();document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>$('#help-dialog').close());
$('#overview').onclick=()=>{world?.overview();sceneCopy();};$('#street').onclick=()=>{world?.street();sceneCopy();};$('#plan').onclick=()=>world?.plan();
$('#orbit').onclick=e=>{const active=world?.orbit();e.currentTarget.classList.toggle('active',active);e.currentTarget.setAttribute('aria-pressed',String(!!active));};
$('#quality').onclick=e=>{const high=world?.quality();e.currentTarget.textContent=high?'高画质':'流畅';toast(high?'高画质：启用环境遮蔽，增强建筑接缝与空间层次。':'流畅模式：保留反射和光影，关闭环境遮蔽。');};
function syncTime(){const playing=!!world?.environment.playing;$('#play-day').textContent=playing?'Ⅱ 暂停':'▶ 演示 24h';$('#play-day').setAttribute('aria-pressed',String(playing));}
$('#time-slider').oninput=e=>{world?.environment.setTime(Number(e.target.value));syncTime();};$('#play-day').onclick=()=>{world?.environment.toggleDay();syncTime();};
$('#water-show').onclick=()=>{world?.overview();world?.environment.show();sceneCopy();toast('水幕为创意预演，19:30 不代表实际场次。');};
try{world=createWorld($('#viewport'),selectPlace);$('#quality').textContent=world.highQuality?'高画质':'流畅';}catch(e){$('#viewport').innerHTML='<div class="error-panel">三维渲染未能启动，请使用支持 WebGL2 的现代浏览器。行程与商家演示仍可操作。</div>';$('#render-state').textContent='三维渲染不可用';console.error(e);}
workbench=createWorkbench({world,toast,onAsset:(name,demo=false,credit=null)=>{document.querySelector('.world').classList.add('asset-view');$('#scene-title').textContent=demo?'先看全景，再选取景。':'现场，正在展开。';$('#scene-subtitle').textContent=name;$('#evidence-chip').textContent=demo?'三维合成全景样例 · 非实拍':'用户素材 · 未配准';$('#scene-note').textContent=demo?'拖动选择方向 · 支持横版与竖版静态取景导出':'用户素材未经校准，不自动生成道路和尺度';$('.time-console').hidden=true;if(credit){$('#scene-title').textContent=credit.reference?'从照片，认识建筑。':'把真实世界，装进开图。';$('#scene-subtitle').textContent=name;$('#evidence-chip').textContent=credit.reference?'人工参考建模 · 非 3DGS':'Insta360 ONE RS · 真实 360° 照片';$('#scene-note').textContent=credit.reference?'印度门 · 主立面照片参考，尺度与遮挡面未验证':credit.author+' / '+credit.license+' · 印度孟买 · 非南京、非 X4 Air';}},onReturn:sceneCopy});
media=createMediaLibrary({world,getVenueId:()=>venueId,onInstaSample:()=>{switchTab('capture');workbench.openRealSample();}});$('#open-media').onclick=()=>media.open();
experience=createExperience({world,toast,switchTab,restoreScene:sceneCopy,assistant:(...args)=>workbench.assistant(...args)});experience.setVenue(venueId);renderRail();render();sceneCopy();
