import './style.css';
import {createWorld} from './scene.js';
import {places,foods,graph,sources} from './data.js';
import {planRoute} from './routing.js';
const $=s=>document.querySelector(s);
let tab='explore',selected='resort',choice='all',world,toastTimer,assetName='',cameraReady=false,recording=false;
const selectedFoods=new Set();
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),6500);}
function setSceneCopy(title,subtitle,chip,note){$('#scene-title').textContent=title;$('#scene-subtitle').textContent=subtitle;$('#evidence-chip').textContent=chip;$('#scene-note').textContent=note;}
const resortCopy=()=>setSceneCopy('一座方舟，万种风味。','仙林水岸 · 空间探索','规划与实景参考 · 待校准','体量与位置为研究示意，路线不可用于现场导航。');
function selectPlace(id){selected=id;world?.focus(id);if(tab!=='explore')switchTab('explore',false);else render();resortCopy();}
function render(){
 const panel=$('#panel');$('.sidebar').className=`sidebar ${tab}`;
 if(tab==='explore'){
  panel.innerHTML=`<h3 class="section-heading">探索目的地 <span>04 PLACES</span></h3>${places.map((p,i)=>`<button class="place ${selected===p.id?'selected':''}" data-place="${p.id}"><span class="place-index">0${i+1}</span><span class="place-text"><strong>${p.name}</strong><small>${p.en}</small></span><span class="place-arrow">↗</span></button>`).join('')}<div class="place-detail"><b>${places.find(p=>p.id===selected).name}</b><br/>${places.find(p=>p.id===selected).detail}</div><button class="primary" id="start-food">开启一场寻味漫游 <span style="float:right">↗</span></button>`;
  panel.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>selectPlace(b.dataset.place));$('#start-food').onclick=()=>switchTab('food');
 }else if(tab==='food'){
  const visible=foods.filter(f=>choice==='all'||f.type===choice);
  panel.innerHTML=`<h3 class="section-heading">今天，想吃点什么？</h3><span class="data-label">示例菜单 · 偏好匹配演示</span><label class="field">我的风味偏好<select id="preference"><option value="all">随心探索 · 全部风味</option><option value="local">金陵风味</option><option value="vegetable">蔬果偏好</option><option value="sweet">甜品时刻</option></select></label><div>${visible.map(f=>`<div class="food-card"><span class="food-symbol">${f.symbol}</span><div class="food-info"><strong>${f.name}</strong><div class="small">${f.counter}</div></div><button data-food="${f.id}" aria-label="${selectedFoods.has(f.id)?'移除':'选择'}${f.name}" aria-pressed="${selectedFoods.has(f.id)}">${selectedFoods.has(f.id)?'✓':'+'}</button></div>`).join('')}</div><div class="small">已选 ${selectedFoods.size} 道 · 菜品及餐台均待现场替换</div><button class="primary" id="route" style="margin-top:15px">生成我的寻味路线 ↗</button><div id="route-result"></div><p class="source-note">当前使用透明的标签匹配与路径算法，尚未接入 AI。真实菜品、配方及过敏原信息需餐厅确认。</p>`;
  $('#preference').value=choice;$('#preference').onchange=e=>{choice=e.target.value;render();};panel.querySelectorAll('[data-food]').forEach(b=>b.onclick=()=>{selectedFoods.has(b.dataset.food)?selectedFoods.delete(b.dataset.food):selectedFoods.add(b.dataset.food);render();});
  $('#route').onclick=()=>{if(!selectedFoods.size){toast('先选择一道想尝试的菜品。');return;}const picked=foods.filter(f=>selectedFoods.has(f.id));const result=planRoute(graph,picked.map(f=>f.node));world?.drawRoute(result.nodes);$('#route-result').innerHTML=`<div class="route-result">从餐厅入口出发<br/>${result.stops.map(s=>foods.find(f=>f.node===s).counter).join(' → ')}<br/><small>沿示例通道计算 · 未进行现实距离标定</small></div>`;toast(`已规划 ${result.stops.length} 个餐台，金色线条表示示例取餐路径。`);};
 }else if(tab==='capture'){
  panel.innerHTML=`<h3 class="section-heading">把现场，带进来。</h3><div class="capture-step"><b>01</b><div>影石采集<small>8K / 30 fps · 慢走闭环<br/>按赛事指南设置，先做小样验证</small></div></div><div class="capture-step"><b>02</b><div>拼接与重建<small>INSV → ERP → 多视角重建<br/>需要独立处理环境</small></div></div><div class="capture-step"><b>03</b><div>导入空间<small>2:1 全景照片 / Gaussian 模型<br/>在浏览器本地读取，不上传素材</small></div></div><label class="upload-zone">＋ 导入实拍资产<input id="asset-file" type="file" accept=".jpg,.jpeg,.png,.webp,.ply,.spz,.splat"/><small>JPG · PNG · WebP · PLY · SPZ · SPLAT</small></label><div id="asset-status" class="small">${assetName?escapeHtml(assetName):'等待第一份真实采集'}</div><div class="actions"><button class="secondary" id="flip">翻转模型</button><button class="secondary" id="return">回到园区</button></div><div class="section-heading" style="margin-top:22px">相机连接 <span>LOCAL BRIDGE</span></div><p class="small" id="camera-state">${cameraReady?'已连接，状态可刷新':'未连接设备 · 仅本地运行可使用相机桥接'}</p><button class="secondary" id="connect">检测影石相机</button><div class="actions"><button class="secondary" id="record-start" ${!cameraReady||recording?'disabled':''}>开始录像</button><button class="secondary" id="record-stop" ${!cameraReady?'disabled':''}>停止录像</button></div><button class="secondary" id="manifest" style="width:100%;margin-top:8px">下载现场采集清单 ↓</button>`;
  $('#asset-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;$('#asset-status').textContent='正在解析，请稍候…';e.target.disabled=true;try{if(!world)throw new Error('当前设备无法创建三维渲染器。');const ext=await world.importAsset(file);assetName=file.name;setSceneCopy('此刻，身在其中。',file.name,['ply','spz','splat'].includes(ext)?'已加载高斯模型':'已加载全景照片','导入素材仅在本机浏览器中读取；尚未与园区坐标配准。');toast('实拍资产已载入，可拖动浏览。');}catch(err){toast(err.message);}finally{if($('#asset-status'))$('#asset-status').textContent=assetName||'未载入新素材';if($('#asset-file'))$('#asset-file').disabled=false;}};
  $('#flip').onclick=()=>{world?.rotateAsset();toast('高斯模型绕 X 轴翻转 180°；全景图片无需翻转。');};$('#return').onclick=()=>{world?.overview();resortCopy();};$('#connect').onclick=connectCamera;$('#record-start').onclick=()=>cameraCommand('start');$('#record-stop').onclick=()=>cameraCommand('stop');$('#manifest').onclick=downloadManifest;
 }else{
  panel.innerHTML=`<h3 class="section-heading">每一处还原，都有依据。</h3><span class="data-label">已找到历史平面 · 尚无竣工测绘图</span>${sources.map(s=>`<a class="source-card" href="${s.url}" target="_blank" rel="noopener noreferrer">${s.title} ↗<small>${s.label}</small></a>`).join('')}<p class="source-note">建筑轮廓参考 2019 年 NO.2018G23 规划转载图；四层弧形立面与绿化裙房结合建成照片校核。原图不构成精确测绘。</p><p class="source-note">示例内容：餐厅位置、餐台布局、菜品、步行路径、地形高程。明天优先采集导览牌、楼层平面及餐厅闭环影像。</p><a class="source-card" href="https://www.prnewswire.com/apac/news-releases/the-first-club-med-urban-oasis-resort-in-the-world-xianlin-nanjing-resort-grand-opens-301961812.html" target="_blank" rel="noopener noreferrer">查看官方供稿的建成实景 ↗<small>PR Newswire · Club Med · 2023</small></a>`;
 }
}
function switchTab(next,move=true){tab=next;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.tab===next));render();if(move){if(next==='food'){world?.restaurant();setSceneCopy('循着风味，找到下一口。','琼林国际餐厅 · 交互体验样板','餐厅示例空间 · 非实测','菜品、餐台及室内路线为演示数据。');}else if(next!=='capture'){world?.overview();resortCopy();}}}
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-Ark-Client':'1'},signal:AbortSignal.timeout(25000)});if(!r.headers.get('content-type')?.includes('application/json'))throw new Error('相机桥接未启动。请在本地运行 npm run bridge，并连接相机 Wi-Fi。');const data=await r.json();if(!r.ok)throw new Error(data.error||'相机请求失败');return data;}
async function connectCamera(){const b=$('#connect');b.disabled=true;$('#camera-state').textContent='正在连接本地桥接与相机…';try{const data=await api('/api/camera/status');cameraReady=!!data.connected;$('#camera-state').textContent=`${data.model} · 电量 ${Math.round((data.battery??0)*100)}%`;$('#record-start').disabled=!cameraReady||recording;$('#record-stop').disabled=!cameraReady;toast('设备已连接。录像使用相机当前设置，请先核对 8K30 参数。');}catch(e){cameraReady=false;$('#camera-state').textContent=e.message;toast(e.message);}finally{if(b)b.disabled=false;}}
async function cameraCommand(action){const btn=$(`#record-${action}`);btn.disabled=true;try{const d=await api(`/api/camera/${action}`,{method:'POST',body:'{}'});recording=action==='start';toast(d.message);$('#camera-state').textContent=recording?'录像中 · 请缓慢移动并完成闭环':'录像已停止 · 原始文件保存在相机';}catch(e){toast(e.message);}finally{$('#record-start').disabled=!cameraReady||recording;$('#record-stop').disabled=!cameraReady;}}
function downloadManifest(){const data={project:'ark-taste-xianlin',schemaVersion:1,createdAt:new Date().toISOString(),evidence:'pending-capture',units:'unregistered',sessions:[{id:'XL-01',zone:'餐厅入口到主餐台',priority:'P0',durationMinutes:'3–5',path:'入口 → 外圈 → 井字通道 → 入口',files:[],status:'todo'},{id:'XL-02',zone:'主餐台细节与菜单',priority:'P0',path:'固定菜品，多高度环绕；菜单正面拍照',files:[],status:'todo'},{id:'XL-03',zone:'导览牌与楼层平面',priority:'P0',path:'正面全图 + 分区近照 + 一段实测距离',files:[],status:'todo'},{id:'XL-04',zone:'主入口与湖岸建筑',priority:'P1',path:'多视角平移，建筑立面保持安全距离',files:[],status:'todo'}],notes:'保留原始 INSV 文件及全部分段。照片补纹理，连续位移视频用于重建。不要把示例坐标用于现场导航。'};const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download='xianlin-capture-manifest.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),500);toast('采集清单已下载。现场按分区编号填写文件名。');}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>switchTab(b.dataset.tab);
$('#help').onclick=()=>$('#help-dialog').showModal();document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>$('#help-dialog').close());
$('#overview').onclick=()=>{world?.overview();resortCopy();};$('#plan').onclick=()=>world?.plan();$('#reset').onclick=()=>{world?.overview();resortCopy();};$('#orbit').onclick=e=>{const active=world?.orbit();e.currentTarget.classList.toggle('active',active);e.currentTarget.setAttribute('aria-pressed',String(!!active));};$('#lighting').onclick=e=>{const active=world?.lighting();$('.world').classList.toggle('night',active);e.currentTarget.classList.toggle('active',active);e.currentTarget.setAttribute('aria-pressed',String(!!active));};
try{world=createWorld($('#viewport'),selectPlace);}catch(e){$('#viewport').innerHTML='<div class="error-panel">此设备未能启动 WebGL2。请使用支持硬件加速的现代浏览器。场地档案与采集清单仍可使用。</div>';$('#render-state').textContent='三维渲染不可用';console.error(e);}
render();
// Optional WebMCP tools share the exact same actions as the visible UI.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
 for(const tool of [
  {name:'get_scene_evidence',description:'Read whether displayed geometry and menus are observed or illustrative.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({geometry:'historic-plan-and-photo-reference',interior:'illustrative',menu:'demo',realCaptureLoaded:!!assetName,view:tab})},
  {name:'navigate_to_place',description:'Move the visible 3D camera to a resort reference location; does not navigate in the real world.',inputSchema:{type:'object',properties:{placeId:{type:'string',enum:places.map(p=>p.id)}},required:['placeId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!places.some(p=>p.id===input.placeId))throw new Error('未知场所');selectPlace(input.placeId);return{selectedPlace:input.placeId,evidence:'reference-model'};}}
 ]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{/* Optional browser capability. */}}
}
