import {escapeHtml as esc,appUrl} from './utils.js';
import {tourProblems,draftCopy} from './tour-model.js';
import {mountTour} from './tour-viewer.js';
import QRCode from 'qrcode';
import './tour.css';
const initial=()=>({title:'影石挑战赛 · 现场实景导览',nodes:[],demo:false,projectId:null,publishedId:null,publishedUrl:'',publishedRevision:-1,revision:0,captureIndex:0,captureDone:[]});
function database(){return new Promise((resolve,reject)=>{const r=indexedDB.open('kaitu-tours',1);r.onupgradeneeded=()=>r.result.createObjectStore('drafts');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function loadDraft(){const db=await database();try{return await new Promise((resolve,reject)=>{const r=db.transaction('drafts').objectStore('drafts').get('current');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}finally{db.close();}}
async function saveDraft(value){const db=await database();try{await new Promise((resolve,reject)=>{const tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').put(value,'current');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}finally{db.close();}}
async function prepareMedia(file){
 if(/\.mp4$/i.test(file.name)){if(file.size>80*1024*1024)throw Error('全景视频浏览副本请控制在 80 MB 内，建议用 Studio 导出 2:1 H.264 MP4 短片。');const url=URL.createObjectURL(file),v=document.createElement('video');v.preload='metadata';v.src=url;try{await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('视频元数据读取超时')),15000);v.onloadedmetadata=()=>{clearTimeout(timer);resolve();};v.onerror=()=>{clearTimeout(timer);reject(Error('无法读取视频，请导出 H.264 MP4'));};});if(Math.abs(v.videoWidth/v.videoHeight-2)>.06)throw Error('视频必须是 Studio 已拼接的 2:1 全景 MP4，不支持原始 INSV 或普通平面视频。');return{blob:file,format:'video'};}finally{v.removeAttribute('src');v.load();URL.revokeObjectURL(url);}}
 return{blob:await prepareImage(file),format:'panorama'};
}
async function prepareImage(file){if(file.size>40*1024*1024)throw Error('单张照片请小于 40 MB，原片可先在 Studio 导出 JPG。');const bmp=await createImageBitmap(file);try{const panorama=Math.abs(bmp.width/bmp.height-2)<.06;if(!panorama)throw Error(file.name+' 不是 2:1 全景图。请用 Studio 导出完整等距柱状 JPG，再导入。');const scale=Math.min(1,4096/bmp.width),c=document.createElement('canvas');c.width=Math.round(bmp.width*scale);c.height=Math.round(bmp.height*scale);c.getContext('2d').drawImage(bmp,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.88));if(!blob)throw Error('图像转换失败');return blob;}finally{bmp.close();}}
async function demoNodes(){const names=['比赛大门（示例）','入口通道（示例）','签到处（示例）','餐厅入口（示例）'];const nodes=[];for(let i=0;i<4;i++){const c=document.createElement('canvas');c.width=2048;c.height=1024;const g=c.getContext('2d');g.fillStyle=['#ccded1','#dce4d6','#e8d7b9','#e4ceb8'][i];g.fillRect(0,0,2048,1024);g.fillStyle='#a9b698';g.fillRect(0,550,2048,474);for(let j=0;j<10;j++){g.fillStyle=j%2?'#fff6dc':'#537565';g.fillRect(j*230,290,130,260);g.fillStyle='#e8edb6';g.fillRect(j*230+18,340,95,90);}g.fillStyle='#294c40';g.fillRect(720,300,600,170);g.fillStyle='#fff6d7';g.textAlign='center';g.font='bold 42px sans-serif';g.fillText(names[i],1020,370);g.font='24px sans-serif';g.fillText('流程插画 · 非现场实拍',1020,420);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.85));nodes.push({id:'demo-'+i,name:names[i],kind:i===3?'food':'place',format:'panorama',blob,description:i===3?'示例餐饮点：可在这里填写餐品、价格和营业时间。当前没有真实套餐或交易。':'这是用于演示点位跳转的插画，不对应真实入口位置。',links:[]});}
 nodes.forEach((n,i)=>{if(i<3)n.links.push({to:nodes[i+1].id,label:['进入会场','前往签到处','查看餐厅入口'][i],yaw:0,pitch:0});if(i>0)n.links.push({to:nodes[i-1].id,label:'返回上一处',yaw:.9,pitch:0});});return nodes;}
export function createTourEditor({toast,legacy}){
 let draft=initial(),step=0,panel,busy=false,ready=false,token='',status='',qr='',pendingAim=null,viewer=null,urls=[],saveQueue=Promise.resolve(),revision=0;
 const captureNames=['比赛大门','入口通道','签到处','餐厅入口'];
 const names=['导入实景','标注连接','完善信息','预览发布'];
 const save=()=>{draft.revision=++revision;const snapshot=structuredClone(draft);saveQueue=saveQueue.catch(()=>{}).then(()=>saveDraft(snapshot));saveQueue.then(()=>{status='草稿已保存在此浏览器';},()=>{status='本机保存失败，请勿关闭页面';toast(status);});};
 loadDraft().then(v=>{if(v){draft=v;revision=v.revision||0;}ready=true;if(panel?.isConnected)render(panel);}).catch(()=>{ready=true;status='此浏览器不能保存草稿，请在关闭前发布';if(panel?.isConnected)render(panel);});
 const request=async(path,options={})=>{const r=await fetch(appUrl('api'+path),{...options,headers:{Authorization:'Bearer '+token,...options.headers},signal:AbortSignal.timeout(120000)});let d;try{d=await r.json();}catch{throw Error('当前站点未启用导览发布服务，请连接完整后台。');}if(!r.ok)throw Error(d.error||'服务请求失败');return d;};
 async function run(fn){if(busy)return;busy=true;render(panel);try{await fn();}catch(e){toast(e.message);status=e.message;}finally{busy=false;if(panel?.querySelector('.tour-editor'))render(panel);}}
 function release(){urls.forEach(URL.revokeObjectURL);urls=[];}
 function source(n){const url=URL.createObjectURL(n.blob);urls.push(url);return url;}
 function preview(edit=false){const errors=tourProblems(draft);if(!draft.nodes.length){toast('请先导入照片或载入示例');return;}if(!edit&&errors.length){toast(errors[0]);return;}const dialog=document.createElement('dialog');dialog.className='tour-dialog';dialog.innerHTML='<button aria-label="关闭导览预览">关闭 ×</button><div class="tour-preview-host"></div>';document.body.append(dialog);let viewUrls=[];const t={...draft,nodes:draft.nodes.map(n=>{const src=URL.createObjectURL(n.blob);viewUrls.push(src);return{...n,src};})};
 viewer=mountTour(dialog.querySelector('.tour-preview-host'),t,{edit,onAim(id,angle){pendingAim={id,...angle};dialog.close();step=1;render(panel);toast('已选择画面位置，选择目标点位后保存热点。');}});const dispose=()=>{viewer?.destroy();viewer=null;viewUrls.forEach(URL.revokeObjectURL);dialog.remove();};dialog.onclose=dispose;dialog.querySelector('button').onclick=()=>dialog.close();dialog.showModal();}
 function render(target){panel=target;release();if(!ready){panel.innerHTML='<p>正在恢复导览草稿…</p>';return;}const issues=tourProblems(draft),options=draft.nodes.map(n=>`<option value="${esc(n.id)}">${esc(n.name)}</option>`).join('');
 const content=[
 ()=>`<h3>把照片变成一份导览。</h3><p>上传 2:1 全景照片或已拼接 MP4，最多 12 个点位。INSP / INSV 请先用影石 Studio 导出。照片生成 4096 像素浏览副本；视频建议 H.264 短片，单个 ≤80 MB。原片请自行备份。</p><div class="capture-guide"><b>拍摄点位动态提醒</b><div class="capture-stops">${captureNames.map((name,i)=>`<button data-capture="${i}" class="${(draft.captureIndex||0)===i?'capture-active':''}" aria-pressed="${(draft.captureIndex||0)===i}">${(draft.captureDone||[]).includes(i)?'✓':'○'} ${name}</button>`).join('')}</div><p role="status">当前建议：${captureNames[draft.captureIndex||0]} · ${(draft.captureIndex||0)===0?'门头正面全景，保留入口方向':(draft.captureIndex||0)===1?'在转角两侧留机位，记录来向与去向':(draft.captureIndex||0)===2?'保留签到台标识，避开个人信息':'拍清餐厅入口，菜单另拍近照'}。</p><small>照片：固定机位、保持水平，人物离开后再拍。视频：建议每点 10–20 秒稳定短片，勿遮挡双镜头。点位为人工采集计划，非设备定位。</small><button class="secondary" data-capture-done>标记当前点已拍 → 提醒下一点</button></div><label class="upload-zone">＋ 导入全景照片 / 视频<input data-files type="file" multiple accept="image/jpeg,image/png,image/webp,video/mp4" ${busy?'disabled':''}/></label><button class="secondary" data-demo ${busy?'disabled':''}>${draft.nodes.length?'用插画示例替换当前草稿':'先体验：大门 → 通道 → 签到 → 餐厅'}</button><p class="tour-note">示例无需填写；全部为流程插画，非现场实拍。你的比赛照片尚未自动进入项目。</p>${draft.nodes.map((n,i)=>`<div class="tour-node-card">${n.format==='video'?'<p>▶ 360° 全景视频 · '+Math.ceil(n.blob.size/1048576)+' MB</p>':`<img src="${source(n)}" alt="${esc(n.name)} 缩略图"/>`}<label>点位 ${i+1}${i===0?' · 导览起点':''}<input data-name="${n.id}" maxlength="60" value="${esc(n.name)}"/></label><div><button class="secondary" data-up="${n.id}" ${i===0?'disabled':''}>设为起点</button><button class="secondary" data-remove="${n.id}">移除点位</button><label>替换全景素材<input type="file" data-replace="${n.id}" accept="image/jpeg,image/png,image/webp,video/mp4"/></label></div></div>`).join('')}`,
 ()=>`<h3>让照片之间有路可走。</h3><p>先打开“定位热点”，拖动照片将门或通道对准中心 ＋，点击“放在视野中心”，再选择要跳转的点位。连接关系需你现场核对，不会自动识别道路。</p><button class="primary" data-position ${draft.nodes.length?'':'disabled'}>打开实景 · 定位热点 ＋</button><label>从哪个点位出发<select data-from>${options}</select></label><label>前往哪个点位<select data-to>${options}</select></label><label>按钮文字<input data-link-label maxlength="60" placeholder="例如：进入会场"/></label><p class="tour-status">${pendingAim?'已选画面位置：'+esc(draft.nodes.find(n=>n.id===pendingAim.id)?.name||''):'尚未定位：保存时放在画面正前方。'}</p><button class="secondary" data-add-link>保存跳转热点</button>${draft.nodes.map(n=>`<div class="tour-node-card"><b>${esc(n.name)}</b>${n.links.map((l,i)=>`<p>${esc(l.label)} → ${esc(draft.nodes.find(v=>v.id===l.to)?.name||'点位已移除')} <button class="secondary" data-del-link="${n.id}:${i}">移除</button></p>`).join('')||'<p>还没有跳转热点</p>'}</div>`).join('')}`,
 ()=>`<h3>让游客看得懂、找得到。</h3><p>标记餐厅并填写已确认的介绍。文字助手根据你输入的名称和说明整理草稿；当前为本地模板，不会识图、调用大模型或编造价格。你可以直接编辑结果。</p>${draft.nodes.map(n=>`<div class="tour-node-card"><b>${esc(n.name)}</b><label>点位用途<select data-kind="${n.id}"><option value="place" ${n.kind==='place'?'selected':''}>入口 / 通道 / 服务点</option><option value="food" ${n.kind==='food'?'selected':''}>餐厅 / 餐饮入口</option></select></label><label>导览 / 餐饮信息<textarea data-description="${n.id}" rows="4" maxlength="1000" placeholder="填写确认过的标识、餐品、价格与营业信息；未知写待确认">${esc(n.description)}</textarea></label><button class="secondary" data-copy="${n.id}">根据已有信息整理介绍草稿</button></div>`).join('')}`,
 ()=>`<h3>交付一份能打开的作品。</h3><p>${draft.nodes.length} 个实景点位 · ${draft.nodes.reduce((s,n)=>s+n.links.length,0)} 个跳转热点 · ${draft.nodes.filter(n=>n.kind==='food').length} 个餐饮点</p>${issues.length?`<div class="tour-errors">发布前请完善：<br/>${issues.map(esc).join('<br/>')}</div>`:'<p>入口可到达全部点位，导览结构检查通过。实际可通行性仍需现场确认。</p>'}<button class="primary" data-preview ${issues.length?'disabled':''}>以游客身份预览 ↗</button><label>后台访问密钥<input data-token type="password" autocomplete="off" placeholder="输入你的后台密码" value="${esc(token)}"/></label><label class="tour-check"><input data-consent type="checkbox"/>我有权公开这些照片，已检查人像和隐私信息，并核对点位连接及餐饮信息。发布后持链接的人可查看导览与所选照片。</label><button class="primary" data-publish ${busy||issues.length?'disabled':''}>${busy?'正在处理，请稍候…':draft.publishedId?'更新这份导览':'发布导览 · 生成链接和二维码'}</button>${draft.publishedUrl?`<div class="tour-share"><b>${draft.publishedRevision===draft.revision?'已发布':'已有发布版 · 草稿修改后请重新发布'}</b><p><a href="${esc(draft.publishedUrl)}" target="_blank" rel="noopener">打开游客导览 ↗</a></p><input readonly aria-label="分享链接" value="${esc(draft.publishedUrl)}"/>${qr?`<img src="${qr}" alt="导览分享二维码"/><a href="${qr}" download="开图导览二维码.png">下载二维码</a>`:''}<button class="secondary" data-copy-url>复制链接</button><button class="secondary" data-unpublish>撤回公开导览</button></div>`:''}`
 ][step]();
 panel.innerHTML=`<div class="tour-editor"><span class="tour-kicker">CAPTURE → CONNECT → SHARE</span><div class="tour-lead"><b>拍一个地方，打开一段旅程。</b><p>最后得到：可环看的实景导览、餐饮入口、分享链接与二维码。</p></div><label>作品名称<input data-title maxlength="100" value="${esc(draft.title)}"/></label><div class="step-nav" role="group" aria-label="导览创作步骤">${names.map((n,i)=>`<button data-step="${i}" aria-current="${step===i?'step':'false'}" ${busy?'disabled':''}>0${i+1}<br/>${n}</button>`).join('')}</div>${content}<div class="work-navigation"><button class="secondary" data-prev ${step===0||busy?'disabled':''}>上一步</button><span>${step+1} / 4</span><button class="secondary" data-next ${step===3||busy?'disabled':''}>下一步</button></div><p class="tour-status" role="status">${esc(status||'本机草稿自动保存 · 密钥只保留在页面内存')}</p><a class="beadring-link" href="http://60.205.204.162/beadring/" target="_blank" rel="noopener">进入豆环 · 把风景拼成纪念 ↗</a><details class="work-details"><summary>高级工具：采集指南、原片与任务管理</summary><p>全景导览无需先做 3DGS 重建。原有工具用于原片处理及技术检查。</p><button class="secondary" data-legacy>打开原片工具</button></details></div>`;
 const $=s=>panel.querySelector(s),bind=(s,fn)=>{const e=$(s);if(e)e.onclick=fn;};
 panel.querySelectorAll('[data-capture]').forEach(b=>b.onclick=()=>{draft.captureIndex=+b.dataset.capture;save();render(panel);});
 bind('[data-capture-done]',()=>{const i=draft.captureIndex||0;draft.captureDone=[...new Set([...(draft.captureDone||[]),i])];draft.captureIndex=captureNames.findIndex((_,n)=>!draft.captureDone.includes(n));if(draft.captureIndex<0){draft.captureIndex=0;toast('四个建议点位均已标记，请导入素材核对清晰度和连接。');}save();render(panel);});
 $('[data-title]').onchange=e=>{draft.title=e.target.value;save();};panel.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{step=+b.dataset.step;render(panel);});bind('[data-prev]',()=>{step--;render(panel);});bind('[data-next]',()=>{step++;render(panel);});
 if($('[data-files]'))$('[data-files]').onchange=e=>{const files=[...e.target.files];run(async()=>{if(draft.nodes.length+files.length>12)throw Error('最多 12 个点位');if(draft.demo&&files.length)throw Error('请先移除示例点位再导入实拍，避免示例与实拍混淆。');for(const f of files){const {blob,format}=await prepareMedia(f);draft.nodes.push({id:crypto.randomUUID?.()||'n'+Date.now()+Math.random().toString(36).slice(2),name:f.name.replace(/\.[^.]+$/,'').slice(0,60),kind:'place',format,description:'',links:[],blob});save();}status='已导入。下一步为照片命名并连接热点。';});};
 bind('[data-demo]',()=>run(async()=>{if(draft.nodes.length&&!confirm('将替换当前本机草稿。已发布的导览不受影响，继续吗？'))return;draft={...initial(),title:'影石挑战赛 · 导览流程示例',demo:true,nodes:await demoNodes()};qr='';save();}));
 panel.querySelectorAll('[data-name]').forEach(el=>el.onchange=()=>{draft.nodes.find(n=>n.id===el.dataset.name).name=el.value;save();});
 panel.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{draft.nodes=draft.nodes.filter(n=>n.id!==b.dataset.remove);draft.nodes.forEach(n=>n.links=n.links.filter(l=>l.to!==b.dataset.remove));if(!draft.nodes.length)draft.demo=false;save();render(panel);});
 panel.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{const i=draft.nodes.findIndex(n=>n.id===b.dataset.up);draft.nodes.unshift(...draft.nodes.splice(i,1));save();render(panel);});
 panel.querySelectorAll('[data-replace]').forEach(el=>el.onchange=e=>{const file=e.target.files[0];if(!file)return;run(async()=>{if(draft.demo)throw Error('示例请先移除后重新导入实拍。');const media=await prepareMedia(file),n=draft.nodes.find(n=>n.id===el.dataset.replace);n.blob=media.blob;n.format=media.format;n.assetId=null;save();});});
 bind('[data-position]',()=>preview(true));if(pendingAim&&$('[data-from]'))$('[data-from]').value=pendingAim.id;
 bind('[data-add-link]',()=>{const from=$('[data-from]').value,to=$('[data-to]').value,n=draft.nodes.find(v=>v.id===from);if(!n||from===to){toast('请选择两个不同点位');return;}if(n.links.length>=12){toast('每个点位最多 12 个热点');return;}const aim=pendingAim?.id===from?pendingAim:{yaw:0,pitch:0};n.links.push({to,label:$('[data-link-label]').value.trim()||'前往'+draft.nodes.find(v=>v.id===to).name,yaw:aim.yaw,pitch:aim.pitch});pendingAim=null;save();render(panel);});
 panel.querySelectorAll('[data-del-link]').forEach(b=>b.onclick=()=>{const [id,i]=b.dataset.delLink.split(':');draft.nodes.find(n=>n.id===id).links.splice(+i,1);save();render(panel);});
 panel.querySelectorAll('[data-kind]').forEach(e=>e.onchange=()=>{draft.nodes.find(n=>n.id===e.dataset.kind).kind=e.value;save();});panel.querySelectorAll('[data-description]').forEach(e=>e.onchange=()=>{draft.nodes.find(n=>n.id===e.dataset.description).description=e.value;save();});
 panel.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>{const n=draft.nodes.find(n=>n.id===b.dataset.copy);n.description=draftCopy(n).slice(0,1000);save();render(panel);toast('已整理本地文字草稿，请核对后发布。');});
 bind('[data-preview]',()=>preview());if($('[data-token]'))$('[data-token]').oninput=e=>token=e.target.value;
 bind('[data-publish]',()=>{if(!$('[data-consent]').checked){toast('请先确认公开发布范围和信息');return;}run(async()=>{if(!token)throw Error('请输入后台密码');if(!draft.projectId){const p=await request('/projects',{method:'POST',body:JSON.stringify({name:draft.title}),headers:{'Content-Type':'application/json'}});draft.projectId=p.id;save();}
 for(const n of draft.nodes){if(n.assetId)continue;status='上传浏览副本：'+n.name;const a=await request('/projects/'+draft.projectId+'/assets?name='+encodeURIComponent(n.name+(n.format==='video'?'.mp4':'.jpg')),{method:'POST',body:n.blob});n.assetId=a.id;save();}
 const d=await request('/tours',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:draft.publishedId||undefined,projectId:draft.projectId,title:draft.title,demo:draft.demo,confirmPublic:true,nodes:draft.nodes.map(({blob,...n})=>n)})});draft.publishedId=d.id;const u=new URL(appUrl(''),location.origin);u.searchParams.set('tour',d.id);draft.publishedUrl=u.href;save();draft.publishedRevision=draft.revision;await saveQueue;await saveDraft(structuredClone(draft));qr=await QRCode.toDataURL(u.href,{width:240,margin:2,color:{dark:'#244d3c',light:'#fffdf2'}});status='发布完成：现在可以把链接或二维码发给别人。';toast(status);});});
 bind('[data-copy-url]',async()=>{try{await navigator.clipboard.writeText(draft.publishedUrl);toast('分享链接已复制');}catch{toast('请选中上方链接手动复制');}});
 bind('[data-unpublish]',()=>run(async()=>{if(!token)throw Error('请输入后台密码');await request('/tours/'+draft.publishedId,{method:'DELETE'});draft.publishedUrl='';qr='';save();status='公开链接已撤回，草稿和原片保留。';}));
 bind('[data-legacy]',()=>{legacy.render(panel);const b=document.createElement('button');b.className='primary';b.textContent='← 返回实景导览创作';b.onclick=()=>render(panel);panel.prepend(b);});
 if(draft.publishedUrl&&!qr)QRCode.toDataURL(draft.publishedUrl,{width:240,margin:2}).then(v=>{qr=v;if(step===3&&panel?.querySelector('.tour-editor')&&!busy)render(panel);});
 }
 return{render,assistant:(venue,query)=>request('/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({venue,query})})};
}
