import * as THREE from 'three';
import {escapeHtml as esc,appUrl} from './utils.js';
import {routeTo} from './tour-model.js';
import './tour.css';
export function mountTour(host,tour,{edit=false,onAim=()=>{},onSelect=()=>{}}={}){
 host.innerHTML=`<div class="tour-shell"><header><span class="tour-brand">开图 / 实景导览</span><h2>${esc(tour.title)}</h2><p>${tour.demo?'插画流程示例 · 非现场实拍 · 不可用于实际导航':'上传者提供的影像与点位连接 · 请以现场标识及通行情况为准'}</p></header><div class="tour-stage"><div class="tour-canvas"></div><img class="tour-flat" alt="" hidden/><div class="tour-hotspots"></div><div class="tour-aim" ${edit?'':'hidden'}>＋</div><span class="tour-hint">拖动环看 · 点击热点前往下一处</span><span class="tour-error" role="status"></span></div><div class="tour-tools">${edit?'<button data-aim>把跳转热点放在视野中心 ＋</button>':''}<button data-video hidden>▶ 播放全景视频</button><button data-food>附近吃什么 ↗</button></div><nav class="tour-nodes" aria-label="实景点位"></nav><article class="tour-info" aria-live="polite"></article><div class="tour-food" hidden></div></div>`;
 const stage=host.querySelector('.tour-stage'),canvas=host.querySelector('.tour-canvas'),hotspots=host.querySelector('.tour-hotspots'),flat=host.querySelector('.tour-flat'),error=host.querySelector('.tour-error');
 let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true});}catch{error.textContent='当前设备无法显示全景，请更换支持 WebGL 的浏览器。';return{destroy(){host.innerHTML='';},select(){}};}
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));canvas.append(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(75,1,.1,100),material=new THREE.MeshBasicMaterial({side:THREE.BackSide}),mesh=new THREE.Mesh(new THREE.SphereGeometry(10,64,32),material);mesh.scale.x=-1;scene.add(mesh);
 let video=null;const videoButton=host.querySelector('[data-video]');
 let current=tour.nodes[0],yaw=0,pitch=0,drag=null,frame,version=0,dead=false;
 const direction=(y,p)=>new THREE.Vector3(Math.cos(p)*Math.sin(y),Math.sin(p),-Math.cos(p)*Math.cos(y));
 const resize=()=>{const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);camera.aspect=w/Math.max(h,1);camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(stage);
 function showFood(){const box=host.querySelector('.tour-food');box.hidden=!box.hidden;if(box.hidden)return;
 box.innerHTML='<h3>餐饮点位</h3><p>“附近”指本导览内已标注的餐饮点；未测量距离，不保证营业。</p>'+tour.nodes.filter(n=>n.kind==='food').map(n=>{const route=routeTo(tour.nodes,current.id,n.id);return `<section><b>${esc(n.name)}</b><p>${esc(n.description)}</p><small>${route?'点位顺序：'+route.map(id=>esc(tour.nodes.find(v=>v.id===id).name)).join(' → '):'当前点位尚无已连接路径'}</small><button data-food-to="${esc(n.id)}">查看餐厅入口</button></section>`;}).join('');
 if(!tour.nodes.some(n=>n.kind==='food'))box.innerHTML+='<p>这份导览还没有标注餐厅。</p>';
 box.querySelectorAll('[data-food-to]').forEach(b=>b.onclick=()=>{select(b.dataset.foodTo);box.hidden=true;});}
 function select(id){const node=tour.nodes.find(n=>n.id===id);if(!node)return;current=node;if(video){video.pause();video.removeAttribute('src');video.load();video=null;}videoButton.hidden=node.format!=='video';yaw=0;pitch=0;const v=++version;error.textContent='正在加载照片…';
 const isPhoto=node.format==='photo';flat.hidden=!isPhoto;canvas.hidden=isPhoto;host.querySelector('.tour-aim').hidden=!edit||isPhoto;
 if(isPhoto){flat.alt=node.name;flat.onload=()=>{if(v===version)error.textContent='';};flat.onerror=()=>{if(v===version)error.textContent='照片加载失败，请刷新或联系发布者。';};flat.src=node.src;}
 else if(node.format==='video'){video=document.createElement('video');video.crossOrigin='anonymous';video.playsInline=true;video.muted=true;video.loop=true;video.preload='metadata';video.src=node.src;const texture=new THREE.VideoTexture(video);texture.colorSpace=THREE.SRGBColorSpace;material.map?.dispose();material.map=texture;material.needsUpdate=true;video.onloadeddata=()=>{if(v===version)error.textContent='';};video.onerror=()=>{if(v===version)error.textContent='视频加载失败，建议导出 H.264 MP4';};videoButton.textContent='▶ 播放全景视频（静音）';videoButton.onclick=async()=>{try{if(video.paused){await video.play();videoButton.textContent='Ⅱ 暂停全景视频';}else{video.pause();videoButton.textContent='▶ 播放全景视频（静音）';}}catch{error.textContent='浏览器无法播放此视频，请更换 H.264 MP4';}};}
 else new THREE.TextureLoader().load(node.src,texture=>{if(dead||v!==version){texture.dispose();return;}texture.colorSpace=THREE.SRGBColorSpace;material.map?.dispose();material.map=texture;material.needsUpdate=true;error.textContent='';},undefined,()=>{if(v===version)error.textContent='全景加载失败，请检查网络或素材。';});
 host.querySelector('.tour-info').innerHTML=`<h3>${esc(node.name)}</h3><p>${esc(node.description||'暂未补充说明。')}</p>`;
 host.querySelector('.tour-nodes').innerHTML=tour.nodes.map(n=>`<button data-node="${esc(n.id)}" aria-current="${n.id===id?'step':'false'}">${n.kind==='food'?'♨ ':''}${esc(n.name)}</button>`).join('');host.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>select(b.dataset.node));
 hotspots.innerHTML=node.links.map((l,i)=>`<button data-hot="${i}" title="${esc(l.label)}">↗ ${esc(l.label)}</button>`).join('');hotspots.classList.toggle('flat-links',isPhoto);hotspots.querySelectorAll('button').forEach(b=>b.onclick=()=>select(node.links[Number(b.dataset.hot)].to));onSelect(node.id);}
 stage.onpointerdown=e=>{if(e.target.closest('button')||current.format==='photo')return;drag={x:e.clientX,y:e.clientY,yaw,pitch};stage.setPointerCapture(e.pointerId);};stage.onpointermove=e=>{if(!drag)return;yaw=drag.yaw-(e.clientX-drag.x)*.004;pitch=THREE.MathUtils.clamp(drag.pitch+(e.clientY-drag.y)*.004,-1.35,1.35);};stage.onpointerup=stage.onpointercancel=()=>drag=null;
 stage.tabIndex=0;stage.setAttribute('aria-label','全景视图，可拖动或使用方向键环看');stage.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)||e.target!==stage)return;e.preventDefault();yaw+=(e.key==='ArrowLeft'?.1:e.key==='ArrowRight'?-.1:0);pitch=THREE.MathUtils.clamp(pitch+(e.key==='ArrowUp'?.1:e.key==='ArrowDown'?-.1:0),-1.35,1.35);};
 host.querySelector('[data-food]').onclick=showFood;const aim=host.querySelector('[data-aim]');if(aim)aim.onclick=()=>onAim(current.id,{yaw:Math.atan2(Math.sin(yaw),Math.cos(yaw)),pitch});
 function loop(){if(dead)return;camera.lookAt(direction(yaw,pitch));camera.updateMatrixWorld();if(current.format!=='photo'){renderer.render(scene,camera);hotspots.querySelectorAll('button').forEach((b,i)=>{const l=current.links[i],d=direction(l.yaw,l.pitch),visible=d.dot(direction(yaw,pitch))>.1,p=d.clone().multiplyScalar(5).project(camera);b.hidden=!visible||Math.abs(p.x)>1||Math.abs(p.y)>1;b.style.left=(p.x*.5+.5)*100+'%';b.style.top=(-p.y*.5+.5)*100+'%';});}frame=requestAnimationFrame(loop);}
 select(current.id);resize();loop();return{select,destroy(){dead=true;version++;if(video){video.pause();video.removeAttribute('src');video.load();}cancelAnimationFrame(frame);observer.disconnect();material.map?.dispose();material.dispose();mesh.geometry.dispose();renderer.dispose();host.innerHTML='';}};
}
export async function openPublishedTour(id){document.title='开图 · 实景导览';document.body.innerHTML='<main class="public-tour"><p role="status">正在打开实景导览…</p></main>';const host=document.querySelector('main');try{const r=await fetch(appUrl('api/public/tours/'+encodeURIComponent(id)));const d=await r.json();if(!r.ok)throw Error(d.error||'导览不可用');d.nodes=d.nodes.map(n=>({...n,src:appUrl(`api/public/tours/${d.id}/assets/${n.assetId}`)}));mountTour(host,d);}catch(e){host.innerHTML=`<h1>暂时无法打开导览</h1><p>${esc(e.message)}</p><a href="${appUrl('')}">返回开图</a>`;}}
