import {escapeHtml as esc,downloadJson} from './utils.js';

const steps=['准备','采集','导入','处理','校准','交付'];
const checks={permission:'确认拍摄范围，避开住客与客房',lens:'擦净双镜头，核对电量与存储',profile:'核对相机参数并拍 20 秒小样',loop:'慢走闭环，有明显平移和重叠',scale:'拍导览牌、楼层图与一段实测距离',overlap:'检查关键入口没有缺拍',review:'检查清晰度、接缝与人物遮挡'};
const key='kaitu-capture-v2';
let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}');}catch{/* Storage may be disabled. */}
const state={step:0,checklist:saved.checklist||{},notes:saved.notes||'',files:[],assetName:'',token:'',project:null,projects:[],cloud:false,busy:false,camera:false,recording:false,startedAt:saved.startedAt||null};
const persist=()=>{try{localStorage.setItem(key,JSON.stringify({checklist:state.checklist,notes:state.notes,startedAt:state.startedAt}));}catch{/* Export still works without storage. */}};
const size=n=>n>=1048576?(n/1048576).toFixed(1)+' MB':Math.ceil(n/1024)+' KB';
const statusNames={queued:'排队中',running:'处理中',succeeded:'已完成',failed:'失败',blocked:'需外部处理'};
export function createWorkbench({world,toast,onAsset,onReturn}){
 let panel=null;
 const $=s=>panel?.querySelector(s);
 const active=()=>panel?.isConnected&&!!$('#workbench');
 const checkRows=ids=>ids.map(id=>`<label class="check-row"><input type="checkbox" data-check="${id}" ${state.checklist[id]?'checked':''}/><span>${checks[id]}</span></label>`).join('');
 async function cloud(path,options={}){
  const response=await fetch('/api'+path,{...options,headers:{...(options.body instanceof File?{}:{'Content-Type':'application/json'}),Authorization:'Bearer '+state.token,...options.headers},signal:AbortSignal.timeout(options.body instanceof File?600000:20000)});
  if(!response.headers.get('content-type')?.includes('application/json'))throw new Error('当前是静态展示。完整工作台请运行云服务，或在现场电脑运行 API。');
  const data=await response.json();if(!response.ok)throw new Error(data.error||'请求失败');return data;
 }
 async function refresh(){if(state.project)state.project=await cloud('/projects/'+state.project.id);if(active())render(panel);}
 async function run(action){if(state.busy)return;state.busy=true;panel?.classList.add('busy');try{await action();}catch(e){toast(e.message);}finally{state.busy=false;panel?.classList.remove('busy');if(active())render(panel);}}
 async function preview(file){if(!world)throw new Error('此设备暂不能创建三维渲染器');await world.importAsset(file);state.assetName=file.name;onAsset(file.name);toast('已载入实拍资产；可拖动浏览，仍需现场配准。');}
 function cameraPanel(){return `<details class="work-details"><summary>可选：连接现场影石相机</summary><p class="small">现场电脑连接相机 Wi‑Fi → 启动 <code>npm run bridge</code> 和开发网页 → 检测设备。在线网站无法穿透相机的局域网；也可以直接按机身录像键。</p><p class="small" id="camera-state">${state.camera?'设备已连接'+(state.recording?' · 录像中':''):'尚未检测设备'}</p><button class="secondary" id="connect-camera">检测设备</button><div class="actions"><button class="secondary" id="start-camera" ${!state.camera||state.recording?'disabled':''}>开始录像</button><button class="secondary" id="stop-camera" ${!state.camera?'disabled':''}>停止录像</button></div><p class="small">使用相机当前模式与参数，不会自动切换为 8K。硬件兼容性需用比赛设备实测。</p></details>`;}
 function cloudPanel(){return `<details class="work-details cloud-panel" ${state.cloud?'open':''}><summary>连接素材与任务服务 <span class="service-dot ${state.cloud?'online':''}"></span></summary><p class="small">素材上传到你部署的服务器。访问密钥只保留在当前页面内存；此演示不包含密钥。</p><label class="field">部署访问密钥<input id="cloud-token" type="password" autocomplete="off" placeholder="粘贴 KAITU_API_TOKEN"/></label><button class="secondary" id="connect-cloud">${state.cloud?'刷新连接':'连接服务'}</button>${state.cloud?`<label class="field">当前场地<select id="cloud-project"><option value="">选择场地</option>${state.projects.map(p=>`<option value="${esc(p.id)}" ${state.project?.id===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><label class="field">新场地名称<input id="project-name" maxlength="100" placeholder="南京仙林 · 首次采集"/></label><button class="secondary" id="create-project">新建场地</button>`:''}${state.project?`<div class="cloud-summary"><b>${esc(state.project.name)}</b><small>${state.project.assets.length} 份素材 · ${state.project.jobs.length} 个任务</small></div><button class="secondary" id="refresh-cloud">刷新素材与任务</button>`:''}</details>`;}
 function assetRows(){return (state.project?.assets||[]).slice(0,80).map(a=>`<div class="asset-row"><b>${esc(a.name)}</b><small>${size(a.bytes)} · ${a.extension.slice(1).toUpperCase()}</small><div class="actions"><button class="secondary" data-job="inspect" data-asset="${a.id}">检查</button>${a.extension==='.mp4'?`<button class="secondary" data-job="extract" data-asset="${a.id}">ERP 抽帧</button>`:''}${['.jpg','.jpeg','.png','.webp','.ply','.spz','.splat'].includes(a.extension)?`<button class="secondary" data-preview="${a.id}">预览</button>`:''}<button class="secondary" data-download="${a.id}">下载</button></div></div>`).join('');}
 const contents=[
 ()=>`<span class="work-kicker">01 / BEFORE YOU WALK</span><h3>先用 20 秒，验证整条链路。</h3><p class="work-lead">目标是让一个区域可浏览、可标注、可交付。先完成主入口到湖岸的小闭环，再扩展整个场地。</p><div class="work-callout">建议 X5 全景视频 8K / 30 fps，最终以赛事指南和设备支持为准。保持曝光与白平衡稳定，优先清晰度。</div>${checkRows(['permission','lens','profile'])}<p class="small">“30 分钟上线”是待实测的产品目标。首次按下「开始记录」计时，最终清单记录实际耗时。</p><button class="primary" id="start-session">${state.startedAt?'采集计时已开始 · 前往采集':'开始记录本次采集 →'}</button>`,
 ()=>`<span class="work-kicker">02 / WALK THE SPACE</span><h3>保持移动，让视角互相重叠。</h3><ol class="work-list"><li><b>主入口 → 湖岸 → 回到入口</b><span>先拍 3–5 分钟小闭环；匀速慢走，镜头保持水平，转弯放慢。</span></li><li><b>建筑与比赛布展</b><span>导览牌正面全图 + 分区近照；入口门头、楼层牌、赛事背景板各拍正面与斜侧面。</span></li><li><b>补结构与尺度</b><span>至少 3 个固定地标，记录一段实测距离；墙角、门框补拍。夜间水幕单独录制，不与白天重建混用。</span></li></ol><button class="secondary" id="capture-path">在模型中显示采集示意线 ↗</button><p class="small">示意线只说明闭环拍法，明天根据实际可走区域调整。</p>${checkRows(['loop','scale','overlap'])}${cameraPanel()}`,
 ()=>`<span class="work-kicker">03 / BRING IT IN</span><h3>原片保留，预览分开。</h3><p class="work-lead">INSV / INSP 保留原文件、双镜头配对与全部分段。全景照片和高斯模型可以直接在右侧查看。</p><label class="upload-zone">＋ 选择现场素材<input id="asset-files" type="file" multiple accept=".insv,.insp,.mp4,.jpg,.jpeg,.png,.webp,.ply,.spz,.splat"/><small>原片 / 2:1 全景 / PLY · SPZ · SPLAT</small></label><div class="file-list">${state.files.length?state.files.map((f,i)=>`<div><span>${esc(f.name)}<small>${size(f.size)}</small></span>${/\.(jpe?g|png|webp|ply|spz|splat)$/i.test(f.name)?`<button class="secondary" data-local-preview="${i}">预览</button>`:'<small>需处理</small>'}</div>`).join(''):'<p class="small">选择文件后不会自动上传。单文件上传上限默认 512 MB；长视频请本地处理后再导入产物。</p>'}</div><p class="small">${state.assetName?'当前预览：'+esc(state.assetName):'未载入实拍；右侧仍是公开资料参考模型。'}</p><div class="actions"><button class="secondary" id="flip-asset">翻转模型</button><button class="secondary" id="back-venue">回到园区</button></div>${cloudPanel()}<button class="primary" id="upload-assets" ${!state.project||!state.files.length?'disabled':''}>上传所选素材到当前场地 ↑</button>`,
 ()=>`<span class="work-kicker">04 / FROM IMAGE TO SPACE</span><h3>每一步，看到真实的状态。</h3><div class="pipeline"><div><b>拼接</b><span>INSV → 2:1 ERP</span><small>影石 Studio / Media SDK · 外部执行</small></div><div><b>检查与抽帧</b><span>尺寸、清晰度、连续视角</span><small>当前 CPU 服务可执行检查和抽帧</small></div><div><b>位姿与重建</b><span>COLMAP / 3DGS → PLY / SPZ</span><small>独立 GPU 流程 · 完成后返回导入</small></div></div><p class="small">不要把鱼眼或未拼接视频直接作为 ERP。GPS / IMU 仅是辅助信息，不能替代相机位姿求解、尺度与楼层校准。</p>${cloudPanel()}${state.project?`<h4 class="section-heading">服务器素材</h4>${assetRows()||'<p class="small">先在「导入」上传素材。</p>'}<h4 class="section-heading">任务记录</h4><div aria-live="polite">${state.project.jobs.map(j=>`<div class="job-row"><span class="job-status ${j.status}">${statusNames[j.status]}</span><b>${j.kind==='inspect'?'素材检查':'ERP 抽帧'}</b><small>${esc(state.project.assets.find(a=>a.id===j.asset_id)?.name||j.asset_id)}</small>${j.error?`<p>${esc(j.error)}</p>`:''}${j.result?`<details><summary>处理结果</summary><pre>${esc(JSON.stringify(j.result,null,2))}</pre></details>`:''}</div>`).join('')||'<p class="small">点击素材旁的「检查」或「ERP 抽帧」提交任务，稍后刷新查看结果。</p>'}</div>`:'<div class="work-callout">未连接后台时，可先用 Studio 在本地拼接，将导出的 2:1 全景导入验证浏览效果。</div>'}`,
 ()=>`<span class="work-kicker">05 / GROUND IT IN REALITY</span><h3>好看之后，还要对得上。</h3><ol class="work-list"><li><b>方向和完整性</b><span>检查地面朝下、接缝无明显错位、入口与楼梯均可辨认。</span></li><li><b>空间锚点</b><span>拍下入口左门框、固定导览牌、湖岸转角；记录楼层、朝向及一段测量距离。</span></li><li><b>布展和服务点位</b><span>补充签到台、舞台、展示区与餐厅名称；以明天的实际布展为准。</span></li></ol>${checkRows(['review'])}<label class="field">现场锚点与实测记录<textarea id="capture-notes" rows="5" maxlength="5000" placeholder="例如：A=主入口左门框；B=导览牌底座；A-B 实测 __ m；所在楼层 __；对应文件名 __">${esc(state.notes)}</textarea></label><div class="work-callout">本版保存配准记录，不自动改变模型尺度。3DGS 是视觉层；可行走道路与楼层关系还需独立核验。</div><button class="secondary" id="save-notes">保存本机记录</button>`,
 ()=>`<span class="work-kicker">06 / UNFOLD THE PLACE</span><h3>交付一个可继续完善的场地。</h3><div class="delivery-summary"><strong>${Object.values(state.checklist).filter(Boolean).length}<span> / 7</span></strong><p>人工检查项已确认<br/><small>${state.startedAt?'采集开始于 '+new Date(state.startedAt).toLocaleTimeString('zh-CN'):'尚未开始采集计时'}</small></p></div><p class="work-lead">清单汇总素材、检查项、锚点与耗时。先用一个真实区域证明“采集 → 可浏览 → 可交付”，再接入导航或其他服务。</p><button class="primary" id="export-local">导出本次采集清单 ↓</button>${state.project?'<div class="actions"><button class="secondary" id="sync-checks">同步检查项</button><button class="secondary" id="export-cloud">导出云端资产清单</button></div>':''}<div class="work-callout">已具备：素材管理、任务检查/抽帧、全景与高斯浏览。待接入验证：AI 语义理解、自动路网、GPU 重建与跨场地调度。</div>`,
 ];
 function render(target){
  panel=target;panel.innerHTML=`<div id="workbench"><div class="work-title"><h3>影像工作台</h3><span>CAPTURE → UNFOLD</span></div><div class="step-nav" role="group" aria-label="采集工作流">${steps.map((s,i)=>`<button data-step="${i}" ${state.step===i?'aria-current="step"':''}><small>0${i+1}</small>${s}</button>`).join('')}</div><div class="work-content">${contents[state.step]()}</div><div class="work-navigation"><button class="secondary" id="prev-step" ${state.step===0?'disabled':''}>← 上一步</button><span>${state.step+1} / 6</span><button class="secondary" id="next-step" ${state.step===5?'disabled':''}>下一步 →</button></div></div>`;
  panel.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>go(Number(b.dataset.step)));
  $('#prev-step').onclick=()=>go(state.step-1);$('#next-step').onclick=()=>go(state.step+1);
  panel.querySelectorAll('[data-check]').forEach(el=>el.onchange=()=>{state.checklist[el.dataset.check]=el.checked;persist();});
  bind('#start-session',()=>{state.startedAt||=new Date().toISOString();persist();go(1);});
  bind('#capture-path',()=>{world?.showCapturePath();onReturn();toast('金色线条为建议闭环拍法，实际位置需现场确认。');});
  bind('#back-venue',()=>{world?.overview();onReturn();});bind('#flip-asset',()=>world?.rotateAsset());
  if($('#asset-files'))$('#asset-files').onchange=e=>{state.files=Array.from(e.target.files);render(panel);};
  panel.querySelectorAll('[data-local-preview]').forEach(b=>b.onclick=()=>run(()=>preview(state.files[Number(b.dataset.localPreview)])));
  bind('#save-notes',()=>{state.notes=$('#capture-notes').value;persist();toast('记录已保存在本机，导出清单会包含这些锚点说明。');});
  bind('#connect-cloud',()=>run(async()=>{state.token=$('#cloud-token').value||state.token;state.projects=(await cloud('/projects')).projects;state.cloud=true;toast('已连接素材服务。请新建或选择一个场地。');}));
  bind('#create-project',()=>run(async()=>{const p=await cloud('/projects',{method:'POST',body:JSON.stringify({name:$('#project-name').value})});state.projects.unshift(p);state.project=p;await refresh();}));
  if($('#cloud-project'))$('#cloud-project').onchange=e=>run(async()=>{state.project=e.target.value?await cloud('/projects/'+e.target.value):null;});
  bind('#refresh-cloud',()=>run(refresh));
  bind('#upload-assets',()=>run(async()=>{for(const file of state.files){toast('正在上传：'+file.name);await cloud('/projects/'+state.project.id+'/assets?name='+encodeURIComponent(file.name),{method:'POST',body:file});}state.files=[];await refresh();toast('素材已持久保存。下一步进入「处理」提交检查任务。');}));
  panel.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>run(async()=>{await cloud('/projects/'+state.project.id+'/jobs',{method:'POST',body:JSON.stringify({assetId:b.dataset.asset,kind:b.dataset.job})});await refresh();toast('任务已排队，处理结果取决于后台 worker 是否运行。');}));
  async function getAsset(id){const a=state.project.assets.find(a=>a.id===id);const r=await fetch('/api/assets/'+id,{headers:{Authorization:'Bearer '+state.token},signal:AbortSignal.timeout(120000)});if(!r.ok)throw new Error('素材下载失败，请重新连接服务');return new File([await r.blob()],a.name,{type:r.headers.get('content-type')});}
  panel.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>run(async()=>preview(await getAsset(b.dataset.preview))));
  panel.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>run(async()=>{const file=await getAsset(b.dataset.download),a=document.createElement('a');a.href=URL.createObjectURL(file);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}));
  bind('#sync-checks',()=>run(async()=>{await cloud('/projects/'+state.project.id+'/checklist',{method:'PUT',body:JSON.stringify(state.checklist)});toast('检查项已同步到当前场地。');}));
  bind('#export-cloud',()=>run(async()=>downloadJson(await cloud('/projects/'+state.project.id+'/manifest'),'kaitu-cloud-manifest.json')));
  bind('#export-local',()=>{downloadJson({schemaVersion:2,project:'开图 Unfold',venue:'南京仙林度假村',exportedAt:new Date().toISOString(),startedAt:state.startedAt,elapsedMinutes:state.startedAt?Math.round((Date.now()-new Date(state.startedAt))/60000):null,targetMinutes:30,targetStatus:'unvalidated',checklist:state.checklist,notes:state.notes,selectedFiles:state.files.map(f=>({name:f.name,bytes:f.size})),previewAsset:state.assetName,cloudProjectId:state.project?.id||null,registration:{status:'pending',units:'unscaled'},captureZones:['主入口与湖岸闭环','赛事背景板、签到与展示区','园区导览牌与楼层平面','一段实测距离与三个固定锚点','夜间水幕独立素材']},'kaitu-capture-manifest.json');toast('采集清单已导出。原始影像请另行备份。');});
  bind('#connect-camera',()=>run(()=>camera('status')));bind('#start-camera',()=>run(()=>camera('start')));bind('#stop-camera',()=>run(()=>camera('stop')));
 }
 function bind(selector,action){const el=$(selector);if(el)el.onclick=action;}
 function go(step){if($('#capture-notes')){state.notes=$('#capture-notes').value;persist();}state.step=Math.max(0,Math.min(5,step));render(panel);panel.closest('.sidebar')?.scrollTo({top:0,behavior:'smooth'});}
 async function camera(action){
  const r=await fetch('/api/camera/'+action,{method:action==='status'?'GET':'POST',headers:{'Content-Type':'application/json','X-Ark-Client':'1'},...(action==='status'?{}:{body:'{}'}),signal:AbortSignal.timeout(25000)});
  if(!r.headers.get('content-type')?.includes('application/json'))throw new Error('请在现场电脑运行相机桥接，连接相机 Wi‑Fi 后再检测。');const d=await r.json();if(!r.ok)throw new Error(d.error||'相机请求失败');
  if(action==='status'){state.camera=!!d.connected;toast(`${d.model||'相机'} · ${state.camera?'连接成功':'未连接'}`);}else{state.recording=action==='start';toast(d.message||'操作完成');}
 }
 return{render,get assetName(){return state.assetName;}};
}
